importcopy
dict importcopy.CONFIG
importcopy.level
importcopy.format
importcopy.filename
tuple[str, str] importcopy.clean_domain(str url)
Extract and clean domain from URL, return both domain and full URL.
Referenced by call_api.
Optional[Dict[str, Any]] importcopy.call_api(str website, Report report)
References clean_domain.
Referenced by process_website.
Dict[str, Any] importcopy.map_company_data(Dict[str, Any] data)
Map agent.ai data to server format.
Referenced by process_website.
bool importcopy.send_to_server(Dict[str, Any] data, TokenManager token_manager)
Send data to server with authentication.
Referenced by process_website.
None importcopy.process_website(str website, Report report, TokenManager token_manager)
Process a single website and send data to server.
References call_api, map_company_data, send_to_server.
None importcopy.process_websites(List[str] websites, TokenManager token_manager)
Process websites with concurrent execution.
Referenced by main.
None importcopy.main()
References main, process_websites.
Referenced by main.